language: generic
sudo: required

services:
    - docker
before_install:
    docker build -t kartik27/docker-app -f Dockerfile.dev .
script:
    - docker run -e CI=true kartik27/docker-app npm run test


deploy:
    provider: elasticbeanstalk
    edge: true
    region: "us-east-2"
    app: "docker-app"
    env: "DockerApp-env"
    bucket_name: "elasticbeanstalk-us-east-2-567886408639"
    bucket_path: "docker-app"
    on:
        branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
            secure: "$AWS_SECRET_KEY"
